---
title: "primacy_effect"
author: "生井沢祥吾"
date: "2024-10-02"
output: html_document
---

# アンケート調査における初頭効果の影響調査
今回の卒論アンケート調査に於いて、ポスターを表示して100点満点で評価してもらう調査手法を実施した。しかし、得点の入力方法がキーボードでの記入ではなく、プルダウン形式による数字選択を行うことで、最初の値が"1"から始まり、昇順に100店まで評価点数を入力してもらう形式となった。

--- 

# ライブラリ読込
```{r}
library(tidyverse)
library(ggplotgui)#ggplot_shiny(exdataset)をコンソールに打ち込んで実行する
library(GGally)
library(plotly)
```

# データの読み込み
```{r}
A1_Dummy <- read_csv("../trash_data/A1_trash.csv")
A1 <- A1_Dummy |>
              select(-PhraseScore) # PhraseScoreカラムを削除

# Is_Participateカラムの”Yes”をアンケートの実施種別を表す”A1”に置換
# Is_Participateカラムはもともとアンケートの協力同意を求める項目で,選択肢は「Yes」しか無い
A1["Is_Participate"] <- lapply(A1["Is_Participate"], gsub, pattern="Yes", replacement = "1点が先頭")
A1

```


```{r}
L <- read_csv("../trash_data/L_trash.csv")

L["Is_Participate"] <- lapply(L["Is_Participate"], gsub, pattern="Yes", replacement = "100点が先頭")


```

# 分析用に２つのデータを結合
```{r}
df_A1_L <- rbind(A1,L)
df_A1_L
```

```{r}
summary(df_A1_L)
```

```{r}

# The code below will generate the graph:
graph <- ggplot(df_A1_L, aes(x = PosterScore)) +
  geom_histogram(position = 'identity', binwidth = 10) +
  facet_grid( . ~ Is_Participate ) +
  theme_bw()


# x軸を 0 から 100 まで 10 間隔でつけ、ラベルもそれぞれ対応する値を指定
graph2 <- graph +
    scale_x_continuous(breaks = seq(0, 100, by = 10),
                     labels = seq(0, 100, by = 10))
graph2
```





